baseURL = 'https://www.roues-libres-charenton.fr/'
languageCode = 'fr-FR'
defaultContentLanguage = 'fr'
timeZone = 'Europe/Paris'
theme = 'm10c'
title = 'Roues Libres Charenton'
enableRobotsTXT = true
timeout = 60000

[params]
author = 'Roues Libres Charenton'
avatar = 'images/RL_LOGO_COULEUR_RVB.jpg'
images = ['images/RL_LOGO_COULEUR_RVB.jpg']

description = "Association d'auto-réparation de vélos"
email = 'contact@roues-libres-charenton.fr'
favicon = '/favicon.ico'
address = '84 Quai des Carrières, 94220 Charenton-le-Pont'
openstreetmap = 'https://www.openstreetmap.org/?mlat=48.82092&mlon=2.40187#map=18/48.82086/2.40188'

[social]
twitter = 'roueslibrescharenton'

[params.rss]
stylesheet = '/rss.xsl'

[params.style]
darkColor = "#222222"
darkestColor = "#3f3e3e"
lightColor = "#dddddd" 
lightestColor = "#E07134"
primaryColor = "#3366FF"

[[params.social]]
icon = "facebook"
name = "RouesLibresCharenton"
url = "https://www.facebook.com/RouesLibresCharenton"

[[params.social]]
icon = "instagram"
name = "RouesLibresCharenton"
url = "https://www.instagram.com/roueslibrescharenton/"

[[params.social]]
icon = "twitter"
name = "@AssoRouesLibres"
url = "https://twitter.com/AssoRouesLibres"

[author]
name = 'Roues Libres Charenton'
email = 'contact@roues-libres-charenton.fr'

[markup.goldmark.renderer]
unsafe = true

[permalinks]
posts = "/:year/:month/:day/:slug/"

[sitemap]
changefreq = "weekly"
