baseURL = 'https://roues-libres-charenton.fr/'
languageCode = 'fr-FR'
defaultContentLanguage = 'fr'
timeZone = 'Europe/Paris'
theme = 'm10c'
title = 'Roues Libres Charenton'
enableRobotsTXT = true

[params]
author = 'Roues Libres Charenton'
avatar = 'images/RL_LOGO_COULEUR_RVB.jpg'
images = ['images/RL_LOGO_COULEUR_RVB.jpg']

description = "Association d'auto-réparation de vélos"
email = 'contact@roues-libres-charenton.fr'
favicon = '/favicon.ico'
#address = '84 Quai des Carrières 94220 Charenton-le-Pont'
#openstreetmap = 'https://www.openstreetmap.org/?mlat=48.82086&mlon=2.40188#map=18/48.82086/2.40188'

[params.style]
darkColor = "#222222"
darkestColor = "#3f3e3e"
lightColor = "#dddddd" 
lightestColor = "#3366FF"
primaryColor = "#E07134"

[[params.social]]
icon = "facebook"
name = "RouesLibresCharenton"
url = "https://www.facebook.com/RouesLibresCharenton"

[[params.social]]
icon = "twitter"
name = "@AssoRouesLibres"
url = "https://twitter.com/AssoRouesLibres"

[[menu.main]]
name = "À propos"
url = "/a-propos"

[[menu.main]]
name = "Mentions légales"
url = "/mentions-legales"
