baseURL = '/'
languageCode = 'fr-fr'
title = 'Roues Libres Charenton'
theme = 'm10c'

[params]
author = 'Roues Libres Charenton'
favicon = 'favicon.ico'
description = "Association d'auto-réparation de vélos"
avatar = 'images/RL_LOGO_COULEUR_RVB.jpg'
email = 'contact@roues-libres-charenton.fr'
#address = '84 Quai des Carrières 94220 Charenton-le-Pont'
#openstreetmap = 'https://www.openstreetmap.org/?mlat=48.82086&mlon=2.40188#map=18/48.82086/2.40188'

[[params.social]]
icon = "facebook"
name = "RouesLibresCharenton"
url = "https://www.facebook.com/RouesLibresCharenton"


[[params.social]]
icon = "twitter"
name = "@AssoRouesLibres"
url = "https://twitter.com/AssoRouesLibres"

[[menu.main]]
  name = "À propos"
  url = "/a-propos"